device: remove use of ccan's endian
When cross compiling with uclibc under buildroot, we get the following
clash:

  ./ccan/endian/endian.h:84:24: error: redefinition of ‘__bswap_32’
   static inline uint32_t bswap_32(uint32_t val)
                          ^
  In file included from usr/include/bits/byteswap.h:1:0,
                   from usr/include/byteswap.h:22,
                   from usr/include/endian.h:59,
                   from usr/include/bits/pthreadtypes.h:21,
                   from usr/include/bits/uClibc_stdio.h:92,
                   from usr/include/stdio.h:71,
                   from libpdbg/device.c:18:
  usr/include/bits/byteswap-common.h:44:1: note: previous definition of ‘__bswap_32’ was here
   __bswap_32 (unsigned int __bsx)
   ^~~~~~~~~~

Work around it by not using ccan's endian. There's only one call site, and we
can use a libc function instead.

Signed-off-by: Joel Stanley <joel@jms.id.au>
Signed-off-by: Alistair Popple <alistair@popple.id.au>