Makefile.am: Disable -Wunused-const-variable for generated file
The shipped gdb parser will fail to build due to this warning and
Werror:

src/gdb_parser_precompile.c:249:18: error: ‘gdb_en_main’ defined but not
used [-Werror=unused-const-variable=]
  249 | static const int gdb_en_main = 97;
      |                  ^~~~~~~~~~~
src/gdb_parser_precompile.c:246:18: error: ‘gdb_first_final’ defined but
not used [-Werror=unused-const-variable=]
  246 | static const int gdb_first_final = 97;
      |                  ^~~~~~~~~~~~~~~
cc1: all warnings being treated as errors

Disable that specific warning like we do for the generated version.

Signed-off-by: Joel Stanley <joel@jms.id.au>