Fix build failure in target detection
CI is failing to build:

 src/options_arm.c:65:3: error: ignoring return value of 'fscanf',
 declared with attribute warn_unused_result [-Werror=unused-result]
    fscanf(cfam_id_file, "0x%" PRIx32, &cfam_id);
    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

If we don't get the expected value in fscanf, display an error. The
code already will do the correct thing and fall through to the unknown
device case.

Signed-off-by: Joel Stanley <joel@jms.id.au>